# Generated by Django 4.0.6 on 2022-08-23 08:13

import ast
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import vehicle.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('logo', models.FileField(upload_to='static/main/images/', validators=[vehicle.validators.validate_file_extension])),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=40)),
                ('status', models.IntegerField()),
                ('rent_per_hour', models.FloatField()),
                ('description', models.TextField()),
                ('image', models.FileField(upload_to='static/main/images/', validators=[vehicle.validators.validate_file_extension])),
                ('brand_id', models.ForeignKey(on_delete=ast.Call, to='vehicle.brands')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_location', models.CharField(default='', max_length=40)),
                ('drop_location', models.CharField(default='', max_length=40)),
                ('pick_date', models.DateField(default=django.utils.timezone.now)),
                ('drop_date', models.DateField(default=django.utils.timezone.now)),
                ('pick_time', models.CharField(max_length=40)),
                ('status', models.IntegerField(default=2)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicles')),
            ],
        ),
    ]
